---
language: ruby
dist: trusty
rvm:
  - 2.0
  - 2.1
  - 2.2.6
  - 2.3.3
  - 2.4.0
branches:
  only:
    - master
sudo: false
cache: bundler
before_install:
  - gem uninstall bundler -a -x
  - gem install bundler -v 1.17.3
